exp_setting:
  exp_name: ''
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  log_every_n_steps: 200
  save_every_n_epochs: 10


dataset:
  name: 'MNIST'
  MNIST:
    name: 'MNIST'
    batch_size: 256
    input_size: 32
    channel: 1
    num_cls: 10
    num_workers: 1
  SVHN:
    name: 'SVHN'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1
  CIFAR10:
    name: 'CIFAR10'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1


model:
  baseline: ['base', 'GNI', 'advGNI', 'dropout', 'mixup', 'cutmix', 'cutout']
  evalmode: ['gaussian', 'color', 'HFC', 'LFC', 'adv_attack']
  MNIST: 'FC' # FC for adversarial noise injection, NormalFC for gaussian noise injection
  SVHN: 'AllCNN'
  CIFAR10: 'AllCNN'

  FC:
    module: [512, 256, 128]
    noise_linear: True
    noise_num_layer: 1
    norm: 'inf' # 'inf' for infnorm penalty. Integer otherwise.
  AllCNN:
    noise_linear: False
    noise_num_layer: 1
    norm: '2'
  cutout:
    length: 16
  mixup:
    alpha: 1.

train:
  num_epochs: 300
  ld:
    MNIST: 0.01
    CIFAR10: 1.
optimizer:
  momentum: 0.9
  lr:
    MNIST: 0.001
    CIFAR10: 0.05
  weight_decay: 0.0005
  lr_decay: 0.99
