exp_setting:
  exp_name: ''
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  log_every_n_steps: 200
  save_every_n_epochs: 100


dataset:
  name: 'CIFAR10'
  MNIST:
    name: 'MNIST'
    batch_size: 256
    input_size: 32
    channel: 1
    num_cls: 10
    num_workers: 1
  SVHN:
    name: 'SVHN'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1
  CIFAR10:
    name: 'CIFAR10'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2616]


model:
  baseline: ['base', 'advGNI', 'advGNI_GA', 'FGSM', 'CURE', 'PGD', 'PGD_hidden', 'FGSM_RS', 'FGSM_GA']
  evalmode: ['adv_attack', 'normal']
  SVHN: 'ResNet'
  CIFAR10: 'Wide_ResNet'

  ResNet:
    eta: 8 # eta/255. will be used following convention
  PGD:
    iters: 7
  advGNI:
    coeff_lower: 0.5
    coeff_higher: 1.
  FGSM_GA:
    coeff: 1.0
  CURE:
    gamma: 8.

train:
  num_epochs: 200
optimizer:
  momentum: 0.9
  lr:
    MNIST: 0.01
    SVHN: 0.01
    CIFAR10: 0.01
  weight_decay: 0.0005
