exp_setting:
  exp_name: ''
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  log_every_n_steps: 200
  save_every_n_epochs: 10


dataset:
  name: 'MNIST'
  MNIST:
    name: 'MNIST'
    batch_size: 256
    input_size: 32
    channel: 1
    num_cls: 10
    num_workers: 1
  SVHN:
    name: 'SVHN'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1

model:
  MNIST: 'FC' # FC for adversarial noise injection, NormalFC for gaussian noise injection
  SVHN: 'CNN'
  adv_train: False
  GNI_in_normal: True
  FC:
    module: [512, 256, 128]
    noise_L: True
    norm: 'inf' # 'inf' for infnorm penalty. Integer otherwise.
    clamp: False # Clamp input noise for fair training

train:
  num_epochs: 100
  ld: 0.02
optimizer:
  momentum: 0.9
  lr: 0.001
  weight_decay: 0.0005
  lr_decay: 0.99
