exp_setting:
  exp_name: ''
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  log_every_n_steps: 200
  save_every_n_epochs: 10


dataset:
  name: 'MNIST'
  MNIST:
    name: 'MNIST'
    batch_size: 256
    input_size: 32
    channel: 1
    num_cls: 10
    num_workers: 1
  SVHN:
    name: 'SVHN'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1
  CIFAR10:
    name: 'CIFAR10'
    batch_size: 128
    input_size: 32
    channel: 3
    num_cls: 10
    num_workers: 1
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2616]


model:
  baseline: ['base', 'GNI', 'advGNI', 'dropout', 'mixup', 'FGSM', 'cutout', 'PGD']
  evalmode: ['adv_attack', 'normal']
  SVHN: 'ResNet'
  CIFAR10: 'ResNet'

  ResNet:
    eta: 0.02
    KL: True
  cutout:
    length: 16
  mixup:
    alpha: 1.
  PGD:
    iters: 7

train:
  num_epochs: 30
  ld:
    MNIST: 0.
    SVHN: 0.
    CIFAR10: 0.1
optimizer:
  momentum: 0.9
  lr:
    MNIST: 0.2
    SVHN: 0.2
    CIFAR10: 0.2
  weight_decay: 0.0005
  lr_decay: 0.99
