exp_setting:
  exp_name: ''
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  log_every_n_steps: 200
  save_every_n_epochs: 100


dataset:
  name: 'CIFAR100'
  CIFAR10:
    name: 'CIFAR10'
    batch_size: 128
    input_size: 32
    padding: 4
    channel: 3
    num_cls: 10
    num_workers: 1
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2616]
  CIFAR100:
    name: 'CIFAR100'
    batch_size: 128
    input_size: 32
    padding: 4
    channel: 3
    num_cls: 100
    num_workers: 1
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2471, 0.2435, 0.2616]


model:
  baseline: ['base', 'advGNI', 'advGNI_GA', 'Free', 'FGSM', 'CURE', 'PGD', 'FGSM_RS', 'FGSM_GA']
  evalmode: ['adv_attack', 'normal']
  SVHN: 'PRN'
  CIFAR10: 'WRN28'
  CIFAR100: 'Res34'

  ResNet:
    eta: 8 # eta/255. will be used following convention
  PGD:
    iters: 7
  FGSM_GA:
    coeff: 1.0
  Free:
    replay: 8
  advGNI:
    alpha: 0.9
    iters: 1
  advGNI_GA:
    alpha: 0.9
    iters: 2

train:
  num_epochs:
    multistep: 200
    cyclic: 30
optimizer:
  momentum: 0.9
  schedule: cyclic #multistep, cyclic
  lr:
    multistep: 0.01
    cyclic: 0.2
  lr_milestone: [60, 120, 160]
  weight_decay: 0.0005
